version: '3'
services:
  osis-portal:
    container_name: osis-portal
    build: ./osis-portal/
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./osis-portal/:/code
    ports:
      - "8001:8000"
    depends_on:
      - db
      - rabbit
      - redis
  osis:
    container_name: osis
    build: ./osis/
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./osis/:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbit
      - redis
  db:
    container_name: osis-db
    image: postgres:9.4
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/init-databases.sh:/docker-entrypoint-initdb.d/init-databases.sh
  rabbit:
    container_name: osis-mq
    image: rabbitmq
  redis:
    container_name: osis-redis
    image: redis:4.0.9
    ports:
      - "6379:6379"
